### ISSUE TITLE
Update Mac Spacemouse driver

### ISSUE THREAD

**Issue by chennes** [FreeCAD/freecad-feedstock#10]
In the Mac code you have:
https://github.com/looooo/freecad-feedstock/blob/2b8a2d4fe0b6619ee8d28133a5892e96f66cff27/recipe/build.sh#L41

The latest driver is:
https://download.3dconnexion.com/drivers/mac/10-7-4_C5CD2A0D-58B6-4A8F-AFD1-54D5EB1BD29C/3DxWareMac_v10-7-4_r3493.dmg

This works on both my Intel and my M2 machine, so I think it's safe to update.

**Comment by adrianinsaval** [comment]
reports on forum claim 10.7.0 worked on arm but further version not.
are these commands correct for both architectures?
https://github.com/FreeCAD/freecad-feedstock/blob/2b8a2d4fe0b6619ee8d28133a5892e96f66cff27/recipe/build.sh#L41-L44

**Comment by adrianinsaval** [comment]
https://github.com/FreeCAD/FreeCAD-Bundle/issues/146#issuecomment-1607208459

please test

**Comment by steffenxx** [comment]
Quick test :-) FreeCAD starts on a Mac Studio, my 3DConnexion devices (SpaceMouse) is directly supported. Files can be opened and creating a MESH is really fast in this version. You are my hero. Thanks a lot

**Comment by adrianinsaval** [comment]
For intel machines I kept the old version for compatibility with mac >=10.12, let me know if it's preferable to stop supporting macOS 10 for a more recent driver
