### ISSUE TITLE
Update MacOS build for ARM

### ISSUE THREAD

**Issue by chennes** [FreeCAD/freecad-feedstock#11]
https://github.com/looooo/freecad-feedstock/blob/b749bd16e65e7caac430aa88699464e693bfc206/recipe/build.sh#L26-L47

This looks like it wants only the Intel chips: I think most of it is relevant to ARM as well, once the SpaceMouse driver is updated.

**Comment by adrianinsaval** [comment]
indeed, [this](https://github.com/adrianinsaval/freecad-feedstock/blob/ca9375d7dd508a8f027f1cdcb45b11dff9f75bc9/recipe/build.sh#L26-L53) at least builds for me, eventually I'll put this in this repo
